set JAVAC="%JAVA_HOME%\bin\javac"
set CLASSPATH=.\;..\Libs\rfa.jar

del /S *.class

%JAVAC% com\reuters\rfa\example\ansipage\*.java
%JAVAC% com\reuters\rfa\example\applet\*.java
%JAVAC% com\reuters\rfa\example\framework\chain\*.java
%JAVAC% com\reuters\rfa\example\framework\idn\*.java
%JAVAC% com\reuters\rfa\example\framework\prov\*.java
%JAVAC% com\reuters\rfa\example\framework\sub\*.java
%JAVAC% com\reuters\rfa\example\omm\domainServer\*.java
%JAVAC% com\reuters\rfa\example\omm\domainServer\marketbyorder\*.java
%JAVAC% com\reuters\rfa\example\omm\domainServer\marketbyprice\*.java
%JAVAC% com\reuters\rfa\example\omm\domainServer\marketmaker\*.java
%JAVAC% com\reuters\rfa\example\omm\domainServer\marketprice\*.java
%JAVAC% com\reuters\rfa\example\omm\domainServer\symbollist\*.java
%JAVAC% com\reuters\rfa\example\omm\idn\newsviewer\*.java
%JAVAC% com\reuters\rfa\example\omm\idn\tsconsole\*.java
%JAVAC% com\reuters\rfa\example\omm\idn\tstrend\*.java
%JAVAC% com\reuters\rfa\example\omm\multipleConsumers\*.java
%JAVAC% com\reuters\rfa\example\omm\dictionary\*.java
%JAVAC% com\reuters\rfa\example\omm\hybrid\*.java
%JAVAC% com\reuters\rfa\example\omm\hybrid\advanced\*.java
%JAVAC% com\reuters\rfa\example\omm\hybrid\simple\*.java
%JAVAC% com\reuters\rfa\example\omm\hybridni\*.java
%JAVAC% com\reuters\rfa\example\omm\itemgroups\*.java
%JAVAC% com\reuters\rfa\example\omm\warmstandbyprov\*.java
%JAVAC% com\reuters\rfa\example\omm\batchviewcons\*.java
%JAVAC% com\reuters\rfa\example\omm\batchviewprov\*.java
%JAVAC% com\reuters\rfa\example\omm\genericmsgcons\*.java
%JAVAC% com\reuters\rfa\example\omm\genericmsgprov\*.java
%JAVAC% com\reuters\rfa\example\omm\postingConsumer\*.java
%JAVAC% com\reuters\rfa\example\omm\postingProvider\*.java
%JAVAC% com\reuters\rfa\example\omm\cons\*.java
%JAVAC% com\reuters\rfa\example\omm\consPerf\*.java
%JAVAC% com\reuters\rfa\example\omm\prov\*.java
%JAVAC% com\reuters\rfa\example\omm\provni\*.java
%JAVAC% com\reuters\rfa\example\omm\sourcemirroringcons\*.java
%JAVAC% com\reuters\rfa\example\omm\sourcemirroringprov\*.java
%JAVAC% com\reuters\rfa\example\omm\symbollist\*.java
%JAVAC% com\reuters\rfa\example\omm\pagedisplay\*.java
%JAVAC% com\reuters\rfa\example\omm\gui\quotelist\*.java
%JAVAC% com\reuters\rfa\example\omm\gui\viewer\*.java
%JAVAC% com\reuters\rfa\example\omm\gui\orderbookdisplay\*.java
%JAVAC% com\reuters\rfa\example\omm\chain\cons\*.java
%JAVAC% com\reuters\rfa\example\omm\chain\prov\*.java
%JAVAC% com\reuters\rfa\example\utility\*.java
%JAVAC% com\reuters\rfa\example\utility\gui\*.java
%JAVAC% com\reuters\rfa\example\omm\privatestream\common\*.java
%JAVAC% com\reuters\rfa\example\omm\privatestream\pscons\*.java
%JAVAC% com\reuters\rfa\example\omm\privatestream\psprov\*.java
%JAVAC% com\reuters\rfa\example\omm\privatestream\psgmcons\*.java
%JAVAC% com\reuters\rfa\example\omm\privatestream\psgmprov\*.java
%JAVAC% com\reuters\rfa\example\quickstart\QuickStartConsumer\*.java
%JAVAC% com\reuters\rfa\example\quickstart\QuickStartProvider\*.java
%JAVAC% com\reuters\rfa\example\quickstart\QuickStartNIProvider\*.java
